/** Spoken by living opponents; copy never consumes combat randomness. */
export type SpeechStage = "opening" | "hit" | "storm" | "miss" | "critical" | "potion" | "revive" | "wounded";

/** Keys match displayed names, lowercased with an initial "The " removed. */
export const MONSTER_OPENINGS: Readonly<Record<string, readonly string[]>> = {
  "grave belle": [
    "You brought a sword to our first date. Finally, some effort.",
    "Come closer. The last one said I seemed distant. Six feet, apparently.",
    "Be honest. Is it the dress, or the exposed rib?",
    "My last admirer gave me his heart. Terrible wrapping, though.",
  ],
  "miss morgue": [
    "Don't stare at my teeth. I picked them out myself.",
    "Do you have a brain, darling? I'm tired of settling.",
    "Tell me I'm radiant. The gravedigger said 'leaking'.",
    "I've been dying to meet someone. Turns out that was the easy part.",
  ],
  "velvet rot": [
    "This dress outlived three husbands. Two were accidents.",
    "Touch the velvet and I'll have you upholstered.",
    "You're staring. Is my jaw on crooked again?",
    "My beauty secret? Sleep, damp soil, and no witnesses.",
  ],
  "lady decomposition": [
    "Kneel. I'd demonstrate, but the knees belong to someone else.",
    "It's not decay. It's an extremely exclusive perfume.",
    "My family has old money. We buried them with it.",
    "Mind your boots. The last guest is still in the rug.",
  ],
  "gary": [
    "Your money or your life! Hang on, which one's easier to carry?",
    "This is a robbery. You do the scared bit. I forgot mine.",
    "Don't scream. You'll wake the competent guards.",
    "Give me your gold. I'll count it later. With help.",
  ],
  "gribnob the unqualified": [
    "My sword training was mostly pointing at a sword.",
    "I've read half the combat manual. You're meant to lose by now.",
    "Nobody ask about my references. Especially my references.",
    "If I win, this counts as experience. If I lose, I was visiting.",
  ],
  "gribble": [
    "Stole this armor off a knight. He still thinks we're hugging.",
    "You can tell I'm important. My helmet has stolen bits on it.",
    "I'm moving up in the world. Mostly by standing on stolen things.",
    "See this sword? Paid nothing for it. Same for the hand that held it.",
  ],
  "gary's supervisor": [
    "If Gary offered you a refund, Gary is also stolen.",
    "I taught Gary everything he knows. Took most of breakfast.",
    "Gary said you were weak. Gary also tried to mug a door.",
    "Your complaint about Gary has been forwarded to Gary.",
  ],
  "thud": [
    "Mum said make an impression. You look soft enough.",
    "I am Thud. Named after the first thing I said to a floor.",
    "You look breakable. That's my favourite kind of visitor.",
    "Hold still. Last one made me run. Ruined a lovely afternoon.",
  ],
  "brutus": [
    "I brought my good axe. Don't make me regret getting it dressed.",
    "My wife says I bottle things up. You're about to get the lid off.",
    "Been told to work on my patience. Stand closer. This'll be quick.",
    "That little shield's adorable. Does it have a parent?",
  ],
  "gronk": [
    "My healer says I carry too much anger. Here. Hold some.",
    "Used to punch walls. Walls never brought me lunch money.",
    "I've got a plan. It fits in one hand and has spikes.",
    "They said find a hobby. Turns out you're exactly hobby-shaped.",
  ],
  "meatwall": [
    "The door was bigger when I took this job.",
    "Go around me. Go on. I'll wait.",
    "They pay me by the hour. I asked for by the pound. They cried.",
    "I don't chase heroes. I stand here until they run out of room.",
  ],
  "dungeon lord": [
    "Wipe your feet. We can kill you without tracking mud in.",
    "You killed my guards? Do you know what recruitment costs?",
    "I had a whole speech. You've arrived in the middle of my soup.",
    "You may take one treasure. By which I mean one look at it.",
  ],
  "senior dungeon lord": [
    "I survived three heroes to get this office. And a much worse deputy.",
    "That cape is far too ambitious for your position.",
    "You defeated my predecessor? Lovely. His chair still squeaks.",
    "I've delegated your death twice. Apparently I must do everything.",
  ],
  "executive overlord": [
    "This isn't stolen gold. It's very successful borrowing.",
    "My door is always open. There's a pit immediately behind it.",
    "We reward initiative here. Then confiscate the reward.",
    "I built this empire from nothing. Specifically, nothing of mine.",
  ],
  "chairman below": [
    "All who oppose me are buried below. Hence the excellent foundations.",
    "My portrait cost more than your village. And complains less.",
    "I own everything you can see. Close your eyes. That's mine too.",
    "You're after my seat? It's cursed. Still better than the pension.",
  ],
};

/** Family order matches MonsterType: zombie, goblin, orc, boss. */
export const FAMILY_REACTIONS: ReadonlyArray<Readonly<Record<SpeechStage, readonly string[]>>> = [
  {
    opening: [
      "You have lovely eyes. Are they firmly attached?",
      "Finally, someone with a pulse and no taste in company.",
      "Don't mind the smell. My perfume has notes of previous tenant.",
      "We can skip dinner. You look like a generous main course.",
    ],
    hit: [
      "You've torn my dress. The woman I took it from will be furious.",
      "Careful with the face. It took three faces to make this one.",
      "You knocked a tooth loose. Fetch it. It's my evening tooth.",
      "Oh, we're doing rough courtship. I should've worn the strong hip.",
      "That was my borrowed spleen. Now I can't give it back.",
      "If you're trying to undress me, there are clasps.",
      "You've opened a seam. Don't look. That's private stuffing.",
      "Leave the cheekbones. They were the entire point of coming back.",
    ],
    storm: [
      "You've singed my lashes. Do you know how hard those are to steal?",
      "Oh, a spark between us. Shame about the smell of cooked hair.",
      "My hair stood up. The rest of me's been trying for years.",
      "You've cooked the worms. Now I have to find new tenants.",
      "You've restarted something. I sincerely hope it's my heart.",
      "Thunder indoors? You flirt like an undertaker with money.",
    ],
    miss: [
      "Was that a spell or a very dramatic sneeze?",
      "Even your lightning won't commit to this relationship.",
      "Try again, dear. The cobweb has had quite enough attention.",
      "All that flashing and not one flattering portrait.",
      "You missed. I'd blush, but I lent those cheeks out.",
      "I've had more thrilling sparks from brushing my burial gown.",
    ],
    critical: [
      "My nose! Put it in something. Not your pocket, something nice.",
      "You've knocked me a decade younger. Horrible decade, mind.",
      "Those legs were a matching pair. You can't get those anymore.",
      "A rib! And we were getting on so well with all of them inside.",
      "You brute. That was the side I let painters see.",
      "Now I have to introduce my shoulder to my arm all over again.",
    ],
    potion: [
      "Drinking alone in front of a lady? Death has better manners.",
      "Does that restore skin? Asking for most of my face.",
      "Save me the bottle. I keep spare fingers in those.",
      "Look at you, keeping your organs on the inside. Show-off.",
      "Your complexion's improving. I find that deeply hurtful.",
      "Don't spill. I just had this floor exhumed.",
    ],
    revive: [
      "Back already? You didn't even dress for the occasion.",
      "One little death and you think we're in the same club.",
      "You kept all your teeth? Clearly you know someone.",
      "Back with both ears? Oh, you paid for the expensive return.",
      "That glow wears off. Then the nose. Usually in that order.",
      "Welcome back. Try not to make undeath look cheap.",
    ],
    wounded: [
      "I'm not falling apart. I'm making myself available in smaller pieces.",
      "Still have my good arm. The one on the floor was for waving.",
      "Don't flatter yourself. Half of that was already loose.",
      "This limp is deliberate. It draws the eye to the shoes.",
      "My jaw can still bite. Someone point it towards you.",
      "If anything else falls off, pretend you didn't notice.",
      "Less of me to love. Same excellent cheekbones.",
      "I'm holding myself together. Literally. Mind the hand.",
    ],
  },
  {
    opening: [
      "Drop your weapons! Gently. They're mine in a minute.",
      "Let's make this easy. You pretend I'm frightening; I take your gold.",
      "Nobody move! Especially me. I've practised this stance.",
      "Empty your pockets. If there's a spider, you can keep that bit.",
    ],
    hit: [
      "Oi! That's stolen property you're damaging. Me included.",
      "The man I stole this armor from said it worked!",
      "Stop denting it. I still need to sell it after.",
      "Hold on. My cowardice hasn't caught up with my mouth.",
      "That's my picking hand! Do you know how many pockets need me?",
      "My uncle warned me about honest work. Should've robbed him instead.",
      "I was about to dodge. You interrupted the thinking bit.",
      "Your sword's worth more without goblin on it. Think about that.",
    ],
    storm: [
      "My hair's on fire! Finally, some height.",
      "Lightning? I was promised people with pockets!",
      "All my stolen spoons! They're touching the same leg!",
      "That's a lot of magic for someone I was robbing quite cheaply.",
      "If I glow in the dark, how am I meant to burgle?",
      "You've melted my lockpicks. That's my entire education gone.",
    ],
    miss: [
      "Ha! I ducked inside my own panic!",
      "You hit the wall. I'll rob it later, see what you've done.",
      "My life flashed before my eyes. Mostly other people's wallets.",
      "Keep aiming there. That's where I keep not being.",
      "Your magic's broken. I'll buy it off you. Very cheap.",
      "I meant to do that. The shriek was part of it.",
    ],
    critical: [
      "My helmet! I'd only just scratched the previous name off!",
      "You hit me so hard I remembered where I hid the rent.",
      "That's going to bruise in shapes I can't spell.",
      "Wait! I know a secret! It's mostly about how scared I am!",
      "I bit my tongue! That's where I keep most of my threats!",
      "My knees have agreed to leave. Without the rest of me.",
    ],
    potion: [
      "No fair. I stole a potion and it was just expensive jam.",
      "Can I have the cork? I'm one cork away from a business.",
      "You're drinking my profit margin!",
      "I've got one of those! It's empty, but the threat's there.",
      "Wait, the bottles are for drinking? I've been throwing mine!",
      "Stop getting healthier. I'm charging the same robbery price.",
    ],
    revive: [
      "Back? Good. Where do you keep the hidden pockets?",
      "I already told the others I won. Be reasonable!",
      "You can't get up. I've mentally spent your boots.",
      "Right. New plan. Same plan, but significantly louder.",
      "Do I have to rob you twice? My bag's not that big.",
      "That's a rotten trick. Teach me before I pretend I invented it.",
    ],
    wounded: [
      "You'll never take me alive! Hang on, that's the one I want.",
      "I'm saving my strength. All three of it.",
      "Nobody tell my mother. She thinks I'm a tax collector.",
      "This is a tactical wobble. Very advanced.",
      "I've still got a trick up my sleeve. Oh. That's blood.",
      "If I look smaller, it's because I've concentrated the danger.",
      "You wouldn't hit a goblin with debts. Think of my creditors.",
      "I could run. But my feet have chosen an awkward time to negotiate.",
    ],
  },
  {
    opening: [
      "Be nice to my axe. It's nervous around new people.",
      "You're early. Haven't stretched my threatening muscles.",
      "We doing this before lunch? I get unpleasant after lunch too.",
      "Talk softly. My club gets jealous when I use words.",
    ],
    hit: [
      "That arm's for carrying kittens. Use the other one.",
      "Hit the shoulder again. Been stiff since Tuesday.",
      "My mother calls that a greeting. She uses a chair.",
      "That tickled. In a horrible way. Do it where I can reach.",
      "Careful. I bruise easily and complain for weeks.",
      "You dented my favorite dent. Now it's just a bump.",
      "Good swing. Awful place to leave your face afterwards.",
      "My little nephew hits harder. We don't let him hold the baby.",
    ],
    storm: [
      "You put weather in my trousers. We are no longer friends.",
      "Good. Needed cooking on this side.",
      "My teeth feel fizzy. Is that normal magic or bad magic?",
      "Stop making my axe hum. It'll want singing lessons.",
      "Smells like pork. Please be you.",
      "Could've just asked me to take the wet armor off.",
    ],
    miss: [
      "I'm the big green one. Try that.",
      "You missed all of me. There's loads of me.",
      "Nice noise. My stomach does that for free.",
      "Was I supposed to fall over? Nobody said.",
      "My grandma aims better. She's an urn.",
      "The ceiling's angry now. Apologize to it.",
    ],
    critical: [
      "You made my knees say a word I don't know.",
      "That's my dinner rib! The one I rest the plate on!",
      "Something clicked. Either I'm fixed or I'm much worse.",
      "I see two of you. Good. Thought I'd packed too much lunch.",
      "That hurt my feelings. They're behind the big rib.",
      "Oh. So that's what a thought feels like.",
    ],
    potion: [
      "You brought a drink and no cup for me? That's the real fight now.",
      "Tiny soup. No bread. You heroes live terribly.",
      "Chew it first. Don't trust food you can't punch.",
      "My healer says drink water. Your healer seems much richer.",
      "Does it come in a bucket? Asking for my mouth.",
      "I had a healing drink once. Turned out I just liked beer.",
    ],
    revive: [
      "Up again? Right. I'll put the rest of my back into it.",
      "That was a short nap. Did you even have a dream?",
      "You're like that cupboard door. Never stays shut.",
      "Good. I hate breaking a thing before I've learned its name.",
      "Can you teach my chair that? Sat on it once. Never recovered.",
      "My turn next. I could use a lie-down with benefits.",
    ],
    wounded: [
      "Not limping. Teaching this leg a lesson.",
      "Still got both fists. And most of the bit between them.",
      "Breathing's loud because I'm doing it with enthusiasm.",
      "My knees are shaking. They're excited to meet your teeth.",
      "Could use a hug. A violent one. With my axe in it.",
      "I've had worse. Mum tried to remove a splinter with a hammer.",
      "Don't count me out. I can't check your numbers.",
      "Fine. You've earned the angry end of the club. Both ends, actually.",
    ],
  },
  {
    opening: [
      "Do make an appointment next time. I like to cancel those.",
      "You're trespassing on very expensive evil.",
      "I see you've brought a sword instead of the correct paperwork.",
      "Welcome. Touch anything and it becomes an additional charge.",
    ],
    hit: [
      "That robe is silk. The screaming is for the silk.",
      "I'll have you know I bruise at a very senior level.",
      "You could have raised this through the suggestion pit.",
      "Mind the rings. They're worth several of my servants.",
      "You're ruining the sleeves I point at people with.",
      "Every scar gets a statue. You're paying for an expensive afternoon.",
      "Stop hitting my left side. That's where I keep my portrait pose.",
      "The last person who touched me like that was knighted. Then buried.",
    ],
    storm: [
      "You've singed the curtains. They're older than your bloodline.",
      "Mind the carpet. It's woven from people with fewer privileges.",
      "You've set fire to my wig. That was a state secret.",
      "All this power and you're still dressed like a lost courier.",
      "My chandelier does that. Admittedly, it has killed fewer guards.",
      "The electricity bill goes to you. So does the electrician's widow.",
    ],
    miss: [
      "Excellent. Someone finally doing less work than my nephew.",
      "You missed. I'll have that painted.",
      "That pillar owed me money. You've done me a kindness.",
      "I've seen more threatening sparks from the budget candlesticks.",
      "A grand entrance with no result. Have you considered management?",
      "You struck an empty chair. Still one of my better advisers.",
    ],
    critical: [
      "That's my signing hand! How am I supposed to ruin lives now?",
      "My crown! There's a very nervous jeweler inside that price tag!",
      "If anyone asks, I received this wound doing something impressive.",
      "You've split my lip. My threats are going to whistle.",
      "I haven't been struck like that since I questioned Mother's rent.",
      "Guards! No, the useful ones! Oh. You've met them.",
    ],
    potion: [
      "That potion is taxable. So is the part of you it repairs.",
      "Swallow quietly. You're making this sound like a public tavern.",
      "Healing yourself? That's exactly the sort of selfishness I admire.",
      "I provide refreshments. They're poisoned, but I do provide them.",
      "You've brought your own bottle. There will be a corkage fee.",
      "My physician charges extra for eye contact. Where did you buy that?",
    ],
    revive: [
      "Resurrection? I'll have to pay the grave digger for a cancellation.",
      "I've already announced my victory. Do try to fit the announcement.",
      "You're alive again. Fine. Your outstanding debts have also returned.",
      "A second chance? I haven't even granted you the first.",
      "Please lie back down. The painter had nearly finished.",
      "You can't simply return. Even my relatives need a reason.",
    ],
    wounded: [
      "I'm bleeding gold. Metaphorically. Stop looking at the floor.",
      "That wobble is hereditary. An excellent family wobble.",
      "My physician said avoid stress. I had him replaced. Several times.",
      "Do not mistake my sweating for agreement.",
      "If I kneel, it's to inspect your extremely taxable boots.",
      "There's a chair behind me, yes? Don't answer with that expression.",
      "You'd be tired too if you carried this much unearned authority.",
      "I'm not begging. I'm offering you the privilege of stopping.",
    ],
  },
] as const;
