export const legacyFrontendSnapshotAbi = [
  {
    inputs: [
      {
        name: "playerAddress",
        type: "address",
      },
    ],
    name: "frontendSnapshot",
    outputs: [
      {
        name: "snapshot",
        type: "tuple",
        components: [
          { name: "hp", type: "uint256" },
          { name: "monsterHp", type: "uint256" },
          { name: "monsterMaxHp", type: "uint256" },
          { name: "roomsCleared", type: "uint256" },
          { name: "gold", type: "uint256" },
          { name: "potions", type: "uint256" },
          { name: "weaponLevel", type: "uint256" },
          { name: "armorLevel", type: "uint256" },
          { name: "monsterType", type: "uint8" },
          { name: "lastLootType", type: "uint8" },
          { name: "lastLootAmount", type: "uint256" },
          { name: "hasStarted", type: "bool" },
          { name: "active", type: "bool" },
          { name: "attackMin", type: "uint256" },
          { name: "attackMax", type: "uint256" },
          { name: "monsterMin", type: "uint256" },
          { name: "monsterMax", type: "uint256" },
          { name: "requestId", type: "uint256" },
          { name: "requestKind", type: "uint8" },
          { name: "playerDamage", type: "uint256" },
          { name: "monsterDamage", type: "uint256" },
          { name: "critical", type: "bool" },
          { name: "campOpen", type: "bool" },
          { name: "restUsed", type: "bool" },
          { name: "campPotionPurchases", type: "uint256" },
          { name: "combatPotionUses", type: "uint256" },
          { name: "supplyOpen", type: "bool" },
          { name: "bandageUsed", type: "bool" },
          { name: "supplyPotionPurchases", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
